CREATE TABLE IF NOT EXISTS raw_bank (
    id SERIAL PRIMARY KEY,
    age INTEGER,
    job VARCHAR(50),
    marital VARCHAR(30),
    education VARCHAR(50),
    default_flag VARCHAR(20),
    housing VARCHAR(20),
    loan VARCHAR(20),
    contact VARCHAR(30),
    month VARCHAR(20),
    day_of_week VARCHAR(20),
    duration INTEGER,
    campaign INTEGER,
    pdays INTEGER,
    previous INTEGER,
    poutcome VARCHAR(50),
    emp_var_rate NUMERIC,
    cons_price_idx NUMERIC,
    cons_conf_idx NUMERIC,
    euribor3m NUMERIC,
    nr_employed NUMERIC,
    y VARCHAR(10)
);
